# Generated by Django 3.2.2 on 2023-09-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_id_number_studentid_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name'], 'verbose_name': 'student'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='student_address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='student_age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
    ]
