# Generated by Django 3.2.2 on 2023-09-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_subject_subjectmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='studentid',
        ),
        migrations.RenameField(
            model_name='studentid',
            old_name='student_id',
            new_name='studentid',
        ),
    ]
