# Generated by Django 3.2.2 on 2023-09-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_genration')},
        ),
    ]
